# Generated by Django 5.1.4 on 2024-12-21 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SKIMS", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="name",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="itemName",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="model",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="refNum",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="vendor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="BinItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("binName", models.CharField(max_length=255, null=True)),
                ("binHeight", models.IntegerField()),
                ("binColor", models.CharField(max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="binName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SKIMS.binitem",
            ),
        ),
        migrations.CreateModel(
            name="HospitalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospitalName", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rackName", models.CharField(max_length=255, null=True)),
                ("binCount", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="binitem",
            name="rackName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SKIMS.rackitem",
            ),
        ),
        migrations.CreateModel(
            name="RoomItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomName", models.CharField(max_length=255, null=True)),
                ("floor", models.IntegerField()),
                ("department", models.CharField(max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "hospitalName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SKIMS.hospitalitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rackitem",
            name="roomName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SKIMS.roomitem",
            ),
        ),
    ]
